Team-QuestMaster/questmaster

Assets/02.Scripts/02-3. Quest/Data.meta
Assets/02.Scripts/02-3. Quest/Data/QuestSO.cs
Assets/02.Scripts/02-3. Quest/Data/QuestSO.cs.meta
Assets/02.Scripts/02-3. Quest/Data/SOData.meta

> QuestSO 초기구현입니다
<br/>
<br/>3분
<br/>
> 필드 타입 괜찮은지 봐주세요
>

Feat | QuestSO 초기구현

---

Assets/02.Scripts/02-2. Adventurer/Data/AdventurerSO.cs
Assets/02.Scripts/02-3. Quest/Data/QuestSO.cs

> 모험가 등급 퀘스트 등급에 주석처리 했습니다
<br/>
<br/>30초
<br/>
>

Comment | 등급주석처리

---

Assets/02.Scripts/02-1. Core/Singleton.cs
Assets/02.Scripts/02-1. Core/Singleton.cs.meta
Assets/02.Scripts/02-20. Util/Tags.cs

싱글톤 제네릭 클래스를 구현하고, Singleton 매니저 GO들을 자식으로 두고 관리할 rootGO가 설정해줄 Singleton 태그를 추가했습니다.
<br/>
<br/>
<br/>
>
싱글톤 제네릭 클래스 채용해도 될까요?

Feat | 싱글톤 제네릭 클래스-최민규

---

Assets/02.Scripts/02-2. Adventurer/Data/AdventurerData.cs
Assets/02.Scripts/02-2. Adventurer/Data/AdventurerData.cs.meta
Assets/02.Scripts/02-2. Adventurer/Data/AdventurerSO.cs
Assets/02.Scripts/02-2. Adventurer/Data/MajorASO.cs
Assets/02.Scripts/02-2. Adventurer/Data/MajorASO.cs.meta
Assets/02.Scripts/02-2. Adventurer/Data/MinorASO.cs
Assets/02.Scripts/02-2. Adventurer/Data/MinorASO.cs.meta
Assets/02.Scripts/02-3. Quest/Data/QuestData.cs
Assets/02.Scripts/02-3. Quest/Data/QuestData.cs.meta
Assets/02.Scripts/02-3. Quest/Data/QuestSO.cs

MajorASO와 MinorASO가 AdventurerSO를 상속하는 구조로 변경, 부모에는 네가지Stat과 AdventurerType만이 존재
MajorASO는 필요한 초기값, MinorASO는 초기값풀이 있습니다.
AdventurerData와 QuestData 구현
current값들 중 불변인 필드와 가변인 필드를 따로 구분해두지는 않았습니다.
<br/>
<br/>
<br/>
>

Feat | MajorMinorSO DataStructure 구현

---

Assets/02.Scripts/02-6. Item/Item.cs
Assets/02.Scripts/02-6. Item/Item.cs.meta
Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/02.Scripts/02-6. Item/ItemManager.cs.meta
Assets/02.Scripts/02-6. Item/TestItem.cs
Assets/02.Scripts/02-6. Item/TestItem.cs.meta

ItemManager, Item 인터페이스, TestItem 구현
ItemManager 기능 : 전체 아이템 리스트 및 보유 아이템 리스트 관리, 인벤토리 칸 수 관리
<br/>
3분
<br/>
<br/>
>

Feat | 아이템매니저,아이템인터페이스구현

---

Assets/02.Scripts/02-4. Calculate/CalculateManager.cs
Assets/02.Scripts/02-4. Calculate/CalculateManager.cs.meta
Assets/02.Scripts/02-9. Date.meta
Assets/02.Scripts/02-9. Date/DateManager.cs
Assets/02.Scripts/02-9. Date/DateManager.cs.meta

CalculateManager(모험가 스탯과 퀘스트 정보를 바탕으로 확률 계산 및 성공여부 판단 담당)와<br/>
DateManager(날짜 관리 및 해당 날짜에 완료될 퀘스트를 저장하고, 해당 날짜에 완료될 퀘스트 리스트를 반환)를 구현했습니다.
<br/>
<br/>
>

Feat | CalculateManager 및 DateManager 구현

---

Assets/01.Scenes/DargTestScene.unity
Assets/02.Scripts/02-9. Drag/DraggableObject.cs
Assets/02.Scripts/02-9. Drag/DraggingObjectSwap.cs
Assets/04.Images/UI/Stamp/2 1.png.meta
Assets/04.Images/UI/Stamp/2 2.png.meta
Assets/04.Images/UI/Stamp/2 3.png.meta
Assets/04.Images/UI/Stamp/2 4.png.meta
Assets/04.Images/UI/Stamp/5 1.png.meta
Assets/04.Images/UI/Stamp/Stamp.png.meta

> 드래그 시 레이어 변경 및 드래그 범위 오류 수정
<br/>
<br/>
<br/>
>

Feat | 드래그레이어-오시현

---

Assets/02.Scripts/02-5. Guild Stat/GuildStatManager.cs
Assets/02.Scripts/02-6. Item/Item.cs
Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/02.Scripts/02-6. Item/TestItems/TestItem.cs
Assets/02.Scripts/02-6. Item/TestItems/TestPassiveStatBuff.cs
Assets/02.Scripts/02-6. Item/TestItems/TestPreventDie.cs
Assets/02.Scripts/02-6. Item/TestItems/TestProbabilityBoost.cs
Assets/02.Scripts/02-6. Item/TestItems/TestReducePenalty.cs
Assets/02.Scripts/02-6. Item/TestItems/TestRewardBoost.cs
Assets/02.Scripts/02-6. Item/TestItems/TestStatBoost.cs

아이템 클래스 구조 변경 : Price 추가, 마우스 오버레이 이벤트 추가(prize오타 수정)
마우스 오버레이 이벤트는 UIManger의 함수를 호출하도록 되어있어서 구현 후 주석처리 빼주시면 될 것 같습니다.
ShopingList라는 버퍼를 상점으로 활용, 복사 버그 막으려고 이렇게 했어요
SellingItems : 3개 추출해서 내놓음
Buy : 내놓은 것 중 하나 가져감
ReturnItems : 남은 것 돌려놓음
길드매니저에 초기값 const로 설정
외에 필드명 약간 수정
<br/>
5분
<br/>
<br/>
>
밤 이벤트 매니저에서 ItemManger에 싱글톤으로 접근한다고 생각하고 만들었습니다. 
이어서 밤 이벤트쪽 제가 만들어보는게 좋을까요?

 Feat | 아이템 상점 구현 및 아이템클래스 구조 변경

---

Assets/02.Scripts/02-1. Core/AudioManager.cs
Assets/02.Scripts/02-1. Core/AudioManager.cs.meta

> 간단한 오디오 매니저 입니당
> 스크립트에 AudioClip만 저장 후 싱글톤으로 불러서 Play하면 사운드가 나오는 형식입니다.
> 원하는 위치에서 sound를 실행시킬 수 있고 delay기능도 있습니다.
> BGM도 가능합니다.
> 볼륨 조절도 가능합니다.
> 추후 필요한 사운드 관련 기능 추가하면 됩니다.
<br/>
<br/>
<br/>
>

Feat | 오디오매니저-오시현

---

Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/02.Scripts/02-7. Night Event/NightEventManager.cs
Assets/02.Scripts/02-7. Night Event/NightEventManager.cs.meta

밤이벤트 매니저 구현 (지금은 거의 비어있음)
구매 확정시 UI에서 ItemManager의 BuyAll을 호출해주시면 됩니다. 
나머지 밤이벤트 매니저 함수는 MainProcess에서 호출해주시면 됩니다. 
+shopping오타수정
<br/>
<br/>
<br/>
>

Feat | NightEventManager구현

---

Assets/02.Scripts/02-3. Quest/Data/QuestData.cs
Assets/02.Scripts/02-3. Quest/Data/QuestSO.cs
Assets/02.Scripts/02-3. Quest/Quest.cs

퀘스트 세부사항을 적어두는 필드 추가
<br/>
30초
<br/>
<br/>
>

Feat | QuestHInt필드 추가

---

Assets/02.Scripts/02-8. UI/ProcessUI/CharacterUI.cs
Assets/02.Scripts/02-9. System/MainProcess.cs

CharacterUI와 시스템 연결을 진행했습니다.
MainProcess의 PickTodayRequests를 통해 오늘 방문할 모험가와 퀘스트 정보를 모두 뽑아온뒤,
CharacterUI에서 관리하는 Characters 리스트에 모험가 gameObject를 추가해줬습니다.
추가적으로 퀘스트 UI 로직이 완성된다면 동일한 방식으로 퀘스트 gameObject를 추가해주거나, Quest 스크립트를 넘겨줄 필요가 있습니다.
<br/>
<br/>

Feat |  CharacterUI와 MainProcess 시스템 연결 - 최민규

---

Assets/02.Scripts/02-8. UI/Show/CalenderManager.cs
Assets/02.Scripts/02-9. System/MainProcess.cs

> MainProcess에서 ApproveRequest() 호출 시 캘린더에 정보 추가
<br/>
<br/>
<br/>
>

Feat | 캘린더데이터표시-오시현

---

Assets/01.Scenes/UIScene.unity
Assets/02.Scripts/02-8. UI/ProcessUI/DayChangeUI.cs
Assets/02.Scripts/02-8. UI/ProcessUI/DayChangeUI.cs.meta
Assets/02.Scripts/02-8. UI/ProcessUI/GuideBookUI.cs
Assets/02.Scripts/02-8. UI/ProcessUI/ReportUI.cs
Assets/02.Scripts/02-8. UI/ProcessUI/UIManager.cs

- 하루의 아침이 시작될 때 보여줄 퀘스트 완료 UI 완성했습니당
<br/>
Report UI가 수정됐어용
<br/>
<br/>
>

Feat | 퀘스트 완료 UI

---

Assets/02.Scripts/02-8. UI/ProcessUI/UIManager.cs
Assets/02.Scripts/02-8. UI/Show/ShowResult.cs
Assets/02.Scripts/02-9. System/MainProcess.cs

> 퀘스트 결과, 수락/거부 결과 UI 연결
<br/>
<br/>
<br/>

Feat | 결과UI-오시현

---

Assets/02.Scripts/02-8. UI/ProcessUI/SettingUI.cs

> 볼륨 조절 이벤트 등록 및 종료 버튼 함수
<br/>
<br/>
<br/>
>

Feat | 설정 기능 추가

---

Assets/02.Scripts/02-2. Adventurer/Data/Dummy/MinorAdventurer.asset
Assets/02.Scripts/02-8. UI/ProcessUI/CharacterUI.cs
Assets/02.Scripts/02-8. UI/Show/AdventurerIDCardUI.cs
Assets/02.Scripts/02-8. UI/Show/AdventurerIDCardUI.cs.meta
Assets/03.Prefabs/UI/Card.prefab

> 모험가 신분증 정보 출력입니당
<br/>
<br/>
<br/>
>

Feat | 모험가 신분증

---

Assets/01.Scenes/UIScene_Mingyu.unity
Assets/03.Prefabs/UI/Card.prefab

> 씬 클래스 참조 오류 해결
<br/>
<br/>
<br/>
>

Fix | 씬 참조 오류해결

---

Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/02.Scripts/02-9. System/MainProcess.cs
ProjectSettings/TagManager.asset

<br/>
ApproveRequest에 "계산 전에"아이템을 사용하고 일시적 효과 아이템의 경우 계산 직후 바로 롤백됩니다. 
<br/>
<br/>
>

Feat | ApproveRequest에 아이템 사용 로직 추가

---

Assets/02.Scripts/02-8. UI/ProcessUI/CharacterUI.cs
Assets/02.Scripts/02-8. UI/ProcessUI/OneDayStartAndEnd.cs
Assets/02.Scripts/02-8. UI/ProcessUI/UIManager.cs
Assets/02.Scripts/02-8. UI/Show/ShowCharacter.cs
Assets/02.Scripts/02-8. UI/Show/ShowResult.cs

Feat | 하루가 끝나면 실행될 이벤트 추가

---

Assets/01.Scenes/UIScene_Youngsuk.unity
Assets/01.Scenes/UIScene_Youngsuk.unity.meta
Assets/03.Prefabs/Items.meta
Assets/03.Prefabs/Items/PreventDie.prefab
Assets/03.Prefabs/Items/PreventDie.prefab.meta
Assets/03.Prefabs/Items/ProbabilityBoost.prefab
Assets/03.Prefabs/Items/ProbabilityBoost.prefab.meta
Assets/03.Prefabs/Items/ReducePenalty.prefab
Assets/03.Prefabs/Items/ReducePenalty.prefab.meta
Assets/03.Prefabs/Items/RewardBoost.prefab
Assets/03.Prefabs/Items/RewardBoost.prefab.meta
Assets/03.Prefabs/Items/StatBoost.prefab
Assets/03.Prefabs/Items/StatBoost.prefab.meta
Assets/03.Prefabs/Items/StatBuff.prefab
Assets/03.Prefabs/Items/StatBuff.prefab.meta

<br/>
아이템 프리팹 추가했습니다. 
<br/>
<br/>
>

Add | 아이템 프리팹 및 아이템 테스트용 씬 추가

---

Assets/02.Scripts/02-8. UI/ProcessUI/CharacterUI.cs
Assets/02.Scripts/02-8. UI/ProcessUI/DayChangeUI.cs
Assets/02.Scripts/02-8. UI/ProcessUI/OneDayStartAndEnd.cs
Assets/02.Scripts/02-8. UI/Show/ShowCharacter.cs

- 인스펙터에 할당이 안 돼있었음
<br/>
<br/>
<br/>
>

Fix | 날짜 넘어가는 부분 버그 고침

---

Assets/02.Scripts/02-8. UI/ProcessUI/CharacterUI.cs
Assets/02.Scripts/02-8. UI/ProcessUI/UIManager.cs

- 오두막집 위에 마우스 커서가 올라오면 길드 수치를 확인할 수 있도록 하였습니다.
<br/>
<br/>
<br/>
>

Feat | 길드 수치 확인 부분 구현

---

Assets/01.Scenes/UIScene_Youngsuk2.unity

Fix | 영석 씬 수정

---

Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/02.Scripts/02-7. Night Event/NightEventManager.cs

<br/>
구현기능 : purchase시 TryBuyall을 통해 현재 자금과 비교 후 부족하면 리턴, 충분하면 구매를 시행 / 구매 성공 시 구매하지 않은 물품 반환
<br/>
<br/>
>

Feat | 구매버튼 클릭 시 로직

---

Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/02.Scripts/02-7. Night Event/NightEventManager.cs

Reverts Team-QuestMaster/questmaster#67

Revert "Feat | 구매버튼 클릭 시 로직"

---

Assets/02.Scripts/02-8. UI/Show/MiniCharacterUI.cs
Assets/04.Images/UI/BackGround/Door.png.meta

미니 캐릭터에 아이템 Appear누락 수정
<br/>
<br/>
<br/>
>

HotFix | 미니 캐릭터에 아이템 Appear누락 수정

---

Assets/02.Scripts/02-9. Drag/DraggingObjectSwap.cs

> 이벤트 함수 순서 오류로 인한 문제 발생 해결
<br/>
<br/>
<br/>
>

HotFix | 메인씬싱글톤오류 해결

---

Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/02.Scripts/02-7. Night Event/NightEventManager.cs
Assets/02.Scripts/02-8. UI/UnderChecker.cs
Assets/03.Prefabs/Items/PreventDie.prefab
Assets/03.Prefabs/Items/ProbabilityBoost.prefab
Assets/03.Prefabs/Items/ReducePenalty.prefab
Assets/03.Prefabs/Items/RewardBoost.prefab
Assets/03.Prefabs/Items/StatBoost.prefab
Assets/03.Prefabs/Items/StatBuff.prefab

<br/>
UnderChecker 아이템오류 수정, 날아간 아이템관련 스크립트2개 복구
<br/>
<br/>
>

Fix | Underchecker오류수정및 날아간 파일2개 복구

---

Assets/01.Scenes/UIScene_Mingyu.unity
Assets/01.Scenes/UIScene_Mingyu.unity.meta
Assets/02.Scripts/02-2. Adventurer/Adventurer.cs
Assets/02.Scripts/02-2. Adventurer/Data/AdventurerData.cs
Assets/02.Scripts/02-2. Adventurer/Data/AdventurerSO.cs
Assets/02.Scripts/02-2. Adventurer/Data/MajorASO.cs
Assets/02.Scripts/02-2. Adventurer/Data/MinorASO.cs
Assets/02.Scripts/02-2. Adventurer/Data/SOData/Dummy/MajorAdventurer_A_SO.asset
Assets/02.Scripts/02-2. Adventurer/Data/SOData/Dummy/MajorAdventurer_B_SO.asset
Assets/02.Scripts/02-2. Adventurer/Data/SOData/Dummy/MajorAdventurer_C_SO.asset
Assets/02.Scripts/02-2. Adventurer/Data/SOData/Dummy/MinorAdventurerSO.asset

1. 작업하신 브랜치가 최신화되었나요? (behind 커밋이 존재하지 않나요?) - Yes
2. 추가하신 기능 및 전체 로직이 정상적으로 동작하는 것을 확인하셨나요? (기능 테스트를 완료하셨나요?) - Yes
3. Scene 내부에 변경사항이 존재한다면, 작업용 Scene에서 추가 혹은 변경한 사항을 메인 Scene에 반영하셨나요? - Yes
<br/>
모험가 데이터 클래스에 SD 스프라이트와 LD 스프라이트 데이터 추가를 진행했습니다.
메이저 모험가는 각 모험가당 1개의 MajorASO가 일대일로 대응합니다.
마이너 모험가는 모든 마이너 모험가가 1개의 MinorASO를 공유합니다. 
따라서 **SD 스프라이트**는 **부모 클래스인 AdventurerSO**에 선언해줬습니다.
(모든 마이너 모험가의 SD 스프라이트는 동일하기 때문입니다.)
**LD 스프라이트**는 **MajorASO 클래스에는 단일 필드**로, **MinorASO 클래스에는 리스트로 추가**했습니다.
(메이저 모험가의 LD는 각각 다르고, 마이너 모험가의 LD도 각각 달라야하지만, 1개의 MinorASO 데이터 클래스에서 랜덤하게 LD를 뽑아와야 하기 때문이다.)
메인 Scene에 반영된 내용은 존재하지 않습니다. 제 작업용 Scene이 변경된 커밋 내역의 경우,
main을 …

Add | 모험가 데이터 클래스에 데이터 추가 - 최민규

---

Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/02.Scripts/02-7. Night Event/NightEventManager.cs
Assets/02.Scripts/02-8. UI/ProcessUI/OneCycleStartAndEnd.cs

<br/>
<br/>
NightMananger 내부에서 NextCycleOptionalEvent에 이벤트 추가하는 구조로 변경
<br/>
<br/>
1분

Fix | 밤에서 낮으로 넘어가도록 수정

---

Assets/01.Scenes/UIScene_Main.unity

1. 작업하신 브랜치가 최신화되었나요? (behind 커밋이 존재하지 않나요?) -네
2. 추가하신 기능 및 전체 로직이 정상적으로 동작하는 것을 확인하셨나요? (기능 테스트를 완료하셨나요?) - 네
3. Scene 내부에 변경사항이 존재한다면, 작업용 Scene에서 추가 혹은 변경한 사항을 메인 Scene에 반영하셨나요? - 네
<br/>
> 메인 씬 버튼 누락 추가
<br/>
<br/>
<br/>

ADD | 메인 씬 Report 닫기 버튼 추가

---

Assets/02.Scripts/02-8. UI/UnderChecker.cs
Assets/02.Scripts/02-9. Drag/DraggableObject.cs
Assets/02.Scripts/02-9. Drag/DraggingObjectSwap.cs

<br/>
> 드래그 종료 이벤트가 드래그를 안하고 클릭만 하면 호출되지 않아 문제가 발생했습니다.
> 때문에 드래그 End가 아닌 PointerUp이벤트로 처리하도록 수정했습니다.
> 액션 명은 기존 OnDragEndEvent에서 OnPointerUpEvent으로 수정되었습니다.
<br/>
<br/>
<br/>

Fix 드래그엔드이벤트오류 오시현

---

Assets/02.Scripts/02-2. Adventurer/Adventurer.cs
Assets/02.Scripts/02-9. System/AdventurerStatHandler.cs
Assets/02.Scripts/02-9. System/AdventurerStatHandler.cs.meta

<br/>
<br/>
AdventurerStatHandler 대충 구현해놨습니다. 랜덤 가중치 주는 알고리즘은 임의로 아무렇게나 일단 해뒀습니다. 씬작업은 안 했습니다. 
<br/>
<br/>
30초

Feat | AdventurerStatHandler추가

---

Assets/01.Scenes/UIScene_Youngsuk.unity
Assets/02.Scripts/02-6. Item/Item.cs
Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/02.Scripts/02-9. Drag/DraggingObjectSwap.cs
Assets/02.Scripts/02-9. System/DateManager.cs

<br/>
<br/>
아이템에 크고작은 오브젝트를 추가해 Swap가능하도록 바꿨습니다. 
큰 오브젝트가 작아질 떄 언더체크가 호출되도록 로직을 수정했습니다. 
SmallObject는 item 스크립트를 갖지 않고 파트너 오브젝트의 item 스크립트를 참조해서 툴팁을 띄웁니다. 
작은 오브젝트는 언더체커가 더이상 필요하지 않습니다. 
메인씬에서는 아직 작업하지 않았습니다. 
<br/>
<br/>

Feat | 아이템에 Swap 기능 구현

---

Assets/02.Scripts/02-2. Adventurer/Data/AdventurerData.cs
Assets/02.Scripts/02-7. Night Event/NightEventManager.cs
Assets/02.Scripts/02-8. UI/Show/ShowCharacter.cs

<br/>
밤이벤트 구매 버튼에 밤이벤트 종료 함수를 호출하도록 이벤트로 연결했습니다. 
<br/>
<br/>
<br/>

Feat | 수락버튼에 밤이벤트 종료이벤트 연결

---

Assets/01.Scenes/UIScene_Youngsuk.unity
Assets/01.Scenes/UIScene_Youngsuk.unity.meta
Assets/02.Scripts/02-2. Adventurer/Data/SOData/Dummy/Dealer_SO.asset
Assets/02.Scripts/02-2. Adventurer/Data/SOData/Dummy/MajorAdventurer_B_SO.asset
Assets/02.Scripts/02-2. Adventurer/Data/SOData/Dummy/MinorAdventurerSO.asset
Assets/02.Scripts/02-8. UI/ProcessUI/CharacterUI.cs

<br/>
상인의 말풍선이 내려가지 않도록 수정했습니다. ShowSpeechBubbleButtonUI가 호출될 때 isClosed가 true로 설정되던 것을 false로 설정되도록 수정했습니다. 
추가로 so데이터를 수정하여 말풍선이 바로 등장하도록 수정했습니다. 
<br/>
<br/>
<br/>

Fix | 상인 말풍선 내려가지 않게 수정, 말풍선 바로 등장하도록 수정

---

Assets/02.Scripts/02-6. Item/ItemManager.cs

<br/>
<br/>
구매시 골드가 부족하면 구매하려는 물품이 좌우로 까딱합니다. 
외에도 구매 성공 및 물품 내놓는 효과를 자연스럽게 수정했습니다. 
<br/>
<br/>

Feat | 골드 부족시 두트윈효과 및 기타 아이템 두트윈 수정

---

Assets/02.Scripts/02-8. UI/ProcessUI/DayChangeUI.cs

1. 작업하신 브랜치가 최신화되었나요? (behind 커밋이 존재하지 않나요?) 네 
<br/>
> 상단 배경이 날이 지나면 초기화 하도록 했습니다.
> DateManager의 OnDateChanged에 초기화 함수를 등록했고 컬러 알파값 뿐만 아니라 _currentStep도 0으로 초기화했습니다.
<br/>
<br/>
<br/>

Fix 상단배경변경 오시현

---

Assets/01.Scenes/UIScene_YS.unity
Assets/01.Scenes/UIScene_YS.unity.meta
Assets/02.Scripts/02-8. UI/ProcessUI/CharacterUI.cs
Assets/04.Images/Character/untitled__4_-removebg-preview.png.meta

<br/>
스피치버블이 상점이 지나간 뒤에도 작동하도록 수정했으며, 더이상 할 말이 없을 때에도 버블이 나오게 수정했습니다. 
<br/>
<br/>
> ![image](https://github.com/user-attachments/assets/70262c5b-b9eb-4d55-9ac7-896ce2b6004a)
캐릭터 버튼 컴포넌트에 ShowSpeechBubbleUIWithPrefix를 온클릭으로 등록해주면 됩니다. 
<br/>

Fix | 스피치버블 오류 수정

---

Assets/01.Scenes/UIScene_Main.unity

<br/>
> 저번 커서 박스 화면 나가는거 적용 후 메인에 적용을 깜빡해서 추가했습니다
<br/>
<br/>
<br/>

Add | 메인 씬 커서 박스 안나가도록 적용

---

Assets/01.Scenes/UIScene_Main.unity
Assets/02.Scripts/02-8. UI/ProcessUI/OneCycleStartAndEnd.cs
Assets/02.Scripts/02-8. UI/ProcessUI/ReportUI.cs
Assets/02.Scripts/02-8. UI/Show/ShowResult.cs
Assets/02.Scripts/02-9. System/MainProcess.cs
Assets/20.External Assets/Super Asset Bundle #2 - Adventure Time v1.5/Updated Paper Book/2 Sprite Sheet/Png/1.png.meta

하루가 변화했을 때의 UI가 변경됐습니다
<br/>
<br/>
하루가 끝나고 나서의 UI를 위와 같이 변경하였습니다.
스탬프 UI에 있던 글자가 옮겨가는 버그를 수정하였습니다.
<br/>
<br/>

Style | 하루 결과 UI변경

---

Assets/02.Scripts/02-6. Item/Item.cs
Assets/02.Scripts/02-8. UI/StampAnimation.cs
Assets/02.Scripts/02-8. UI/UnderChecker.cs
Assets/ProjectSettings/UIEffectPresets.meta
Assets/ProjectSettings/UIEffectPresets/ItemShiny.prefab
Assets/ProjectSettings/UIEffectPresets/ItemShiny.prefab.meta
Assets/ProjectSettings/UIEffectPresets/ItemUse.prefab
Assets/ProjectSettings/UIEffectPresets/ItemUse.prefab.meta
Assets/ProjectSettings/UIEffectProjectSettings.asset

<br/>
> 아이템 사용 효과 및 사용 준비 효과를 동적으로 들어가게 수정했습니다.
> 도장에서 클릭을 떼는 순간 아이템 사용 효과가 보여집니다.
<br/>
<br/>
<br/>

Feat | 아이템비쥬얼효과-오시현

---

Assets/02.Scripts/02-3. Quest/Data/SOData/01. GreenTierQuest/QuestSO_Bruna2.asset
Assets/02.Scripts/02-3. Quest/Data/SOData/01. GreenTierQuest/QuestSO_Elderwin2.asset
Assets/02.Scripts/02-3. Quest/Data/SOData/01. GreenTierQuest/QuestSO_Lumiel2.asset
Assets/02.Scripts/02-3. Quest/Data/SOData/01. GreenTierQuest/QuestSO_Lumiel3.asset
Assets/02.Scripts/02-3. Quest/Data/SOData/01. GreenTierQuest/QuestSO_Zerdin1.asset

<br/>
게임 초반 1~3일 차에 등장할 Green 등급 퀘스트가 의도한대로 등장하도록 클리어 기준 전투력과 보상을 조정했습니다.
<br/>
<br/>

Refactor | 그린 등급 퀘스트 1~3일차 퀘스트 데이터 변경

---

Assets/02.Scripts/02-6. Item/ItemManager.cs
Assets/04.Images/MiniCharacter/ChatGPT_Image_2025년_4월_12일_오후_09_34_19-removebg-preview.png.meta
Assets/04.Images/MiniCharacter/image-removebg-preview (3).png.meta
Assets/04.Images/UI/BackGround/BackFrame.png.meta
Assets/04.Images/UI/BackGround/Gemini_Generated_Image_tcyufltcyufltcyu.jpg.meta
Assets/04.Images/UI/BackGround/MainScene 1.png.meta
Assets/04.Images/UI/SpeachBubble.png.meta

1. 작업하신 브랜치가 최신화되었나요? (behind 커밋이 존재하지 않나요?)네
2. 추가하신 기능 및 전체 로직이 정상적으로 동작하는 것을 확인하셨나요? (기능 테스트를 완료하셨나요?)네
3. Scene 내부에 변경사항이 존재한다면, 작업용 Scene에서 추가 혹은 변경한 사항을 메인 Scene에 반영하셨나요?네
<br/>
<br/>
출현한 적 있던 아이템의 두트윈이 남아있어서 재출현할 때 보이지 않는 버그를 수정했습니다. 
추가로 아이템 출현을 조금더 크게 변경했습니다.
<br/>
<br/>

Fix | 아이템 재출현 버그 수정

---

Assets/02.Scripts/02-6. Item/ItemManager.cs

<br/>
<br/>
아이템 사용 후 RemainList에 추가하지 않습니다. 
<br/>
<br/>

Fix | 사용한 아이템 재등장하지 않게 수정

---

Assets/01.Scenes/EndingScene.unity
Assets/01.Scenes/UIScene_Main.unity
Assets/02.Scripts/02-8. UI/ProcessUI/EndingJudge.cs
Assets/02.Scripts/02-9. System/MainProcess.cs
Assets/04.Images/StartImage/MainStartScene.png.meta
Assets/04.Images/StartImage/StartSceneImage.png.meta

1. 작업하신 브랜치가 최신화되었나요? (behind 커밋이 존재하지 않나요?) ㅖ
2. 추가하신 기능 및 전체 로직이 정상적으로 동작하는 것을 확인하셨나요? (기능 테스트를 완료하셨나요?) ㅖ
3. Scene 내부에 변경사항이 존재한다면, 작업용 Scene에서 추가 혹은 변경한 사항을 메인 Scene에 반영하셨나요? ㅖ
<br/>
<br/>
1. 가이드북의 확률에 해당하는 부분의 색감을 조정하였습니다
2. 엔딩씬의 버튼 색감을 조절하였습니다.
<br/>
<br/>

Style 약간의 색감 조정

---

.gitattributes
lionterassociation.zip

.zip 파일을 LFS에서 트래킹하도록 설정하고, 빌드 .zip 파일을 추가했습니다.
없습니다.
<br/>

Add | 게임빌드파일.zip 추가 및 LFS .zip 트래킹 설정 - 최민규
